### ISSUE TITLE
ACPI Sleep States S3 S4 S5

### ISSUE THREAD

**Issue by ForceTower** [thejoaov/EFI-e5-573g-7415-Mojave-10.14.6#1]
Cara, to travado nesse erro faz horas...
Como vc conseguiu passar dele?
o.o

**Comment by thejoaov** [comment]
Configura a bios
Tem que colocar o dvmt com 128mb
Desativar a placa de vídeo e usar só a do processador
E desligar o vt-x

Em sáb, 4 de abr de 2020 20:20, João Sena <notifications@github.com>
escreveu:

**Comment by ForceTower** [comment]
Obrigado, tu ainda tem o link de onde tu baixou tudo?
pq eu to baixando uma imagem atras da outra aqui tbm... 

Desculpa o incomodo tbm man :/

**Comment by thejoaov** [comment]
baixei pelo olarila mesmo.
Se tu quiser, dá uma olhada em outro repositório meu que tem o efi do
catalina

Em sáb, 4 de abr de 2020 21:05, João Sena <notifications@github.com>
escreveu:

**Comment by ForceTower** [comment]
Wlw cara, consegui com o catalina 10.15.4

O Mojave não ia de jeito nenhum :o
Wlw mesmo! Teus repo salvou d+
